# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170215_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
