# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:52
from __future__ import unicode_literals

from django.db import migrations, models

from tags.models import Tag

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170303_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),        
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='tags.Tag'),
        ),
    ]
