# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=256)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='categories.Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tags.Tag')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
