# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_description'),
        ('posts', '0004_auto_20170307_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='categories.Category'),
        ),
    ]
